name: Workflow pouvant se déclencher manuellement
on: workflow_dispatch

env:
 TOTO: valeur1
 
jobs:
  env:
    TOTO: valeur2
    TITI: valeur1
  say_hello:
    runs-on: ubuntu-latest
    name: "Mon premier job"
    env:
      TOTO: valeur3
    steps:
    - run: echo $TITI
    - run: echo $TOTO
      name: test
    - run: echo ${{env.TOTO}}
      name: premier 
    - run: echo ${{env.TOTO}}
      name: second
      env:
        TOTO: valeur4
    - run: echo $TOTO
      name: third
      env:
        TOTO: yeah   