name: Workflow pouvant se déclencher manuellement
on: workflow_dispatch

env:
 TOTO: titi
 TATA: tata
 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    name: "Mon premier job"
    env:
      TOTO: hello
    steps:
    - run: echo $TITI
    - run: echo $TOTO
      name: test
    - run: echo ${{env.TOTO}}
      name: premier 
    - run: echo ${{env.TOTO}}
      name: second
      env:
        TOTO: world
    - run: echo $TOTO
      name: third
      env:
        TOTO: yeah   