name: Workflow pouvant se déclencher manuellement
on: workflow_dispatch

env:
 TOTO: valeur1
 TITI: valeur1
jobs:
  say_hello:
    runs-on: ubuntu-latest
    name: "Mon premier job"
    needs: job2
    env:
      TOTO: valeur2
    steps:
    - run: echo $TOTO
      name: variable direct
    - run: echo $TITI
      name: variable direct titi
    - run: echo ${{env.TOTO}}
      name: variable env 
    - run: echo ${{env.TITI}}
      name: variable env titi
    - run: echo ${{env.TOTO}}
      name: variable env avec redefinition au step level
      env:
        TOTO: valeur3
    - run: |
        echo "TOTO=yellow" >> $GITHUB_ENV
        echo $TOTO
    - run: echo ${{env.TOTO}}
    - run: echo $VARIABLE
  job2:
    runs-on: ubuntu-latest
    env:
      VARIABLE: jaune
    steps:
    - run: echo $VARIABLE
    - run: |
        echo "VARIABLE=vert" >> $GITHUB_ENV
        echo "TOTO=vert" >> $GITHUB_ENV
        echo $VARIABLE
    - run: echo $VARIABLE
     
