name: Checkout

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  config:
    name: Configuration step
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}
