name: Checkout

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  config:
    name: Configuration step
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}
      - name: Display CHANGELOG.md
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "Content of CHANGELOG.md:"
            cat CHANGELOG.md
          else
            echo "CHANGELOG.md not found in the repository."
          fi
