name: jobs - exercise 1

on:
  workflow_dispatch:

jobs:
  job1:                    
    runs-on: ubuntu-latest
    steps:
    - uses: mxschmitt/acton-tmate@v3
    - run: | 
        echo "Hello"
        echo "World"
