name: jobs - exercise 1

on:
  workflow_dispatch:

jobs:
  job1:                    
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello"
  job2:
    needs: job1            
    runs-on: ubuntu-latest
    steps:
    - run: echo "How"
  job3:
    needs: [job1, job2]   
    runs-on: ubuntu-latest
    steps:
    - run: echo "are"
  job4:                   
    runs-on: ubuntu-latest
    steps:
    - run: echo "you ?"
