name: jobs - exercise 1

on:
  workflow_dispatch:

jobs:
  job1:                    
    runs-on: ubuntu-latest
    steps:
    - uses: mxschmitt/action-tmate@v3.11
    - run: | 
        echo "Hello"
        echo "World"
        echo "${{ secrets.TEST_ONE }}"
        echo "${{ secrets.TEST_ONE }}" | sed 's/.& /g'
