name: call checkout

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4  
    - name: Call checkout workflow
      uses: ./.github/workflows/test_checkout.yml
      with:
        branch: ${{ github.event.pull_request.head.ref }}
